site_name: 'P4wnP1 Official Wiki'
site_author: 'Swiftb0y'
repo_url: 'https://github.com/mame82/P4wnP1_aloa/'
edit_uri: '../P4wnP1-Wiki/edit/master/docs/'
#site_favicon: 'img/logo_P4wnP1_favicon.svg'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.keys
  - toc:
      permalink: True


theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'img/logo_P4wnP1_favicon.svg'
  language: 'en'
  feature:
    tabs: false
  font:
    code: 'monospace'
  social:
    - type: 'github'
      link: 'https://github.com/mame82'
    - type: 'twitter'
      link: 'https://twitter.com/P4wnP1'

nav:
- Overview: 'index.md'
- Quickstart: 'Quickstart.md'
- 'USB Features': 'USB-Features.md'
- 'Web UI': 'Web-UI.md'
- Wireless:
  - Overview: 'Wireless/Overview.md'
  - WiFi:
    - Overview: 'Wireless/WiFi/Overview.md'
    - AP: 'Wireless/WiFi/AP.md'
    - Client: 'Wireless/WiFi/Client.md'
    - Nexmon KARMA: 'Wireless/WiFi/Nexmon-KARMA.md'
    - Covert Channel: 'Wireless/WiFi/Covert-Channel.md'
  - Bluetooth:
    - Overview: 'Wireless/Bluetooth/Overview.md'
    - PAN: 'Wireless/Bluetooth/PAN.md'
    - NAP: 'Wireless/Bluetooth/NAP.md'
    - PANU: 'Wireless/Bluetooth/PANU.md'
- Scripting:
  - Overview: 'Scripting/Overview.md'
  - HIDScript:
    - Overview: 'Scripting/HIDScript/Overview.md'
    - Tutorials: 'Scripting/HIDScript/Tutorials.md'
    - 'Command Reference': 'Scripting/HIDScript/Command-Reference.md'
  - 'P4wnP1 CLI':
    - Overview: 'Scripting/P4wnP1-CLI/Overview.md'
    - Quickstart: 'Scripting/P4wnP1-CLI/Quickstart.md'
    - 'Command Reference': 'Scripting/P4wnP1-CLI/Command-Reference.md'
    - Bash: 'Scripting/P4wnP1-CLI/Bash.md'
  - 'Web UI':
    - Overview: 'Scripting/Web-UI/Overview.md'
    - TriggerActions:
      - Overview: 'Scripting/Web-UI/TriggerActions/Overview.md'
      - Tempates: 'Scripting/Web-UI/TriggerActions/Templates.md'
      - 'Master Templates': Scripting/Web-UI/TriggerActions/Master-Templates.md
      - Tutorials: 'Scripting/Web-UI/TriggerActions/Tutorials.md'
      - Reference: 'Scripting/Web-UI/TriggerActions/Reference.md'
      - Templates: 'Scripting/Web-UI/TriggerActions/Deploying-Templates.md'
- Contributing:
  - Guidelines: 'Contributing/Guidelines.md'
  - P4wnP1 A.L.O.A:
    - Overview: 'Contributing/P4wnP1-ALOA/Overview.md'
    - Tool Architecture: 'Contributing/P4wnP1-ALOA/Tool-Architecture.md'
    - Core Architecture: 'Contributing/P4wnP1-ALOA/Core-Architecture.md'
    - Web UI Architecture: 'Contributing/P4wnP1-ALOA/Web-UI-Architecture.md'
  - Wiki: 'Contributing/Wiki.md'
  - ToDo: 'Contributing/ToDo.md'
- FAQ: 'FAQ.md'
- Troubleshooting: 'Troubleshooting.md'
- Credits: 'Credits.md'
