site_name: 'P4wnP1 Official Wiki'
site_author: 'Swiftb0y'
repo_url: 'https://github.com/mame82/P4wnP1/'
edit_uri: '../P4wnP1-Wiki/edit/master/docs/'
#site_favicon: 'img/logo_P4wnP1_favicon.svg'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.keys
  - toc:
      permalink: True


theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'img/logo_P4wnP1_favicon.svg'
  language: 'en'

extra:
  font:
    code: 'monospace'
  social:
    - type: 'github'
      link: 'https://github.com/mame82'
    - type: 'twitter'
      link: 'https://twitter.com/P4wnP1'

nav:
- Home: 'index.md'
- FAQ: 'FAQ.md'
- Getting Started:
  - Installation: 'Getting-Started-Subfolder/Installation.md'
  - 'Getting Started': 'Getting-Started-Subfolder/Getting-Started.md'
  - Setup.cfg: 'Getting-Started-Subfolder/Setup.cfg.md'
- Payloads:
  - Overview: 'Payload-Subfolder/Payload-Home.md'
  - Backdoor:
    - Payload: 'Payload-Subfolder/Backdoor-Subfolder/Backdoor-Payload.md'
    - 'Commandline Interface': 'Payload-Subfolder/Backdoor-Subfolder/Backdoor-Commands.md'
  - 'Wifi Covert Channel': 'Payload-Subfolder/Wifi-Covert-Channel.md'
  - Frontdoor: 'Payload-Subfolder/Frontdoor-Payload.md'
  - Windows 10 Lockpicker:
    - Payload: 'Payload-Subfolder/Windows-10-Lockpicker-Subfolder/Windows-10-Lockpicker.md'
    - Technical Writeup: 'Payload-Subfolder/Windows-10-Lockpicker-Subfolder/writeup_lockpicker.md'
  - 'Stealing Browser Credentials': 'Payload-Subfolder/Stealing-Browser-Credentials.md'
- 'OS Independent features': 'OS-independent-features-Subfolder/OS-independent-features-Home.md'
- 'P4wnP1 W exclusive features':
  - Overview: 'P4wnP1-W/RasPi0-W-Home.md'
  - 'Wifi Hotspot': 'P4wnP1-W/Wifi-Hotspot.md'
  - 'Wifi Client': 'P4wnP1-W/Wifi-Client.md'
  - 'Bluetooth': 'P4wnP1-W/Bluetooth-Connectivity.md'
  - 'Reverse SSH tunnel': 'P4wnP1-W/AutoSSH.md'
  - 'Wifi Covert Channel': 'Payload-Subfolder/Wifi-Covert-Channel.md'
- Troubleshooting: 'Troubleshooting.md'
- 'Advanced Features': 'Advanced-Features.md'
- Contributing:
    - Contributing: 'Contributing-Subfolder/Contributing-Home.md'
    - 'Payload Development': 'Contributing-Subfolder/Module-development.md'
    - 'Other ways to Contribute': 'Contributing-Subfolder/Other-Ways-to-Contribute.md'
    - 'Logo Suggestions': 'Contributing-Subfolder/Logo-Suggestions.md'
- 'Wiki TODO list': 'ToDo.md'
