site_name: 'P4wnP1 Official Wiki'
site_author: 'Swiftb0y'
repo_url: 'https://github.com/mame82/P4wnP1/'
edit_uri: '../P4wnP1-Wiki/edit/master/docs/'
#site_favicon: 'img/logo_P4wnP1_favicon.svg'

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.keys
  - toc:
      permalink: True


theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    primary: 'blue'
    accent: 'blue'
  logo: 'img/logo_P4wnP1_favicon.svg'
  language: 'en'
  feature:
    tabs: false
  font:
    code: 'monospace'
  social:
    - type: 'github'
      link: 'https://github.com/mame82'
    - type: 'twitter'
      link: 'https://twitter.com/P4wnP1'

nav:
- Overview: 'Index.md'
- Quickstart: 'Quickstart.md'
- USB Features: 'USB-Features.md'
- Web-UI: 'Web-UI.md'
- Wireless: 'Wireless/Index.md'
  - WiFi: 'Wireless/WiFi/Index.md'
    - AP: 'Wireless/WiFi/AP.md'
    - Client: 'Wireless/WiFi/Client.md'
    - Nexmon KARMA: 'Wireless/WiFi/Nexmon-KARMA.md'
    - Covert Channel: 'Wireless/WiFi/Covert-Channel.md'
  - Bluetooth: 'Wireless/Bluetooth/Index.md'
    - PAN: 'Wireless/Bluetooth/PAN.md'
    - NAP: 'Wireless/Bluetooth/NAP.md'
    - PANU: 'Wireless/Bluetooth/PANU.md'
- Scripting: 'Scripting/Index.md'
  - HIDScript: 'Scripting/HIDScript/Index.md'
    - Tutorials: 'Scripting/HIDScript/Tutorials.md'
    - Command Reference: 'Scripting/HIDScript/Command-Reference.md'
  - P4wnP1 CLI: 'Scripting/P4wnP1-CLI/Index.md'
    - Quickstart: 'Scripting/P4wnP1-CLI/Quickstart.md'
    - Command Reference: 'Scripting/P4wnP1-CLI/Command-Reference.md'
  - Web UI: 'Scripting/Web-UI/Index.md'
    - TriggerActions: 'Scripting/Web-UI/Index.md'
     - Deploying Templates: 'Scripting/Web-UI/Deploying-Templates.md'
     - Tutorials: 'Scripting/Web-UI/Tutorials.md'
     - Reference: 'Scripting/Web-UI/Reference.md'
  - Bash: 'Scripting/Bash.md'
- Contributing: 'Contributing/Index.md'
  - P4wnP1 A.L.O.A: 'Contributing/P4wnP1-ALOA/Index.md'
    - Tool Architecture: 'Contributing/P4wnP1-ALOA/Tool-Architecture.md'
    - Core Architecture: 'Contributing/P4wnP1-ALOA/Core-Architecture.md'
    - Web UI Architecture: 'Contributing/P4wnP1-ALOA/Web-UI-Architecture.md'
  - Wiki: 'Contributing/Wiki.md'
  - ToDo: 'Contributing/ToDo.md'
- FAQ: 'FAQ.md'
- Troubleshooting: 'Troubleshooting.md'
- Credits: 'Credits.md'
